[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["python311 -m pip install --upgrade pip", "python311 -m pip install -r requirements.txt"]

[start]
cmd = "python app.py"